# Generated by Django 4.0.4 on 2022-05-30 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='works',
            old_name='works_id',
            new_name='work_id',
        ),
    ]
