# Generated by Django 4.0.4 on 2022-05-30 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0003_rename_works_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='summary',
        ),
        migrations.AddField(
            model_name='work',
            name='Detail',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='Title',
            field=models.CharField(default='', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
