# Generated by Django 4.0.4 on 2022-05-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0004_remove_work_summary_work_detail_work_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='Detail',
            field=models.TextField(null=True),
        ),
    ]
