# Generated by Django 4.0.4 on 2022-05-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('works', '0005_alter_work_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='gitbool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='gitlink',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='work',
            name='livebool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='livelink',
            field=models.URLField(blank=True),
        ),
    ]
